[package]
name = "async-h1"
version = "1.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rustasync/async-h1"
documentation = "https://docs.rs/async-h1"
description = "Asynchronous HTTP 1.1 parser."
keywords = ["async", "http", "stream", "parser", "http1"]
categories = ["asynchronous", "parser-implementations", "web-programming", "web-programming::http-client", "web-programming::http-server"]
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
readme = "README.md"
edition = "2018"

[dependencies]
httparse = "1.3.3"
http = "0.1.17"
futures-io = "0.3.0"
async-std = { version = "0.99.12", features = ["unstable"] }
futures-core-preview = "0.3.0-alpha.18"

[dev-dependencies]
futures-util = "0.3.0"
pretty_assertions = "0.6.1"
